name: HTML Tidy
on: [pull_request]
jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tidy
        run: sudo apt-get update && sudo apt-get install -y tidy
      - name: Run tidy
        run: |
          find . -name '*.html' -print0 | xargs -0 -n 1 tidy -q -e
